services:
  app:
    image: ghcr.io/${OWNER}/personal-website:${IMAGE_TAG}
    container_name: personal_website
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      NEXT_PUBLIC_MAPS_PUBLIC_KEY: ${NEXT_PUBLIC_MAPS_PUBLIC_KEY}
      NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION}
      NEXT_PUBLIC_MAINTENANCE_MODE: ${NEXT_PUBLIC_MAINTENANCE_MODE}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      ML_API_BASE_URL: ${ML_API_BASE_URL}
      ML_API_KEY: ${ML_API_KEY}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}
      ANALYTICS_LOG_RETENTION_DAYS: ${ANALYTICS_LOG_RETENTION_DAYS:-180}
      ANALYTICS_HASH_SALT: ${ANALYTICS_HASH_SALT}
      CHAT_LOG_RETENTION_DAYS: ${CHAT_LOG_RETENTION_DAYS:-365}
      CHAT_LOG_MAX_TEXT_CHARS: ${CHAT_LOG_MAX_TEXT_CHARS:-4000}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.personal-website.rule=Host(`mathislambert.fr`)"
      - "traefik.http.routers.personal-website.entrypoints=websecure"
      - "traefik.http.routers.personal-website.tls=true"
      - "traefik.http.routers.personal-website.tls.certresolver=letsencrypt"
      - "traefik.http.services.personal-website.loadbalancer.server.port=3000"
    networks: [proxy, databases, monitor]

networks:
  proxy:
    external: true
  databases:
    external: true
  monitor:
    external: true
