services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: personal_frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.personal-frontend.rule=Host(`mathislambert.fr`,`www.mathislambert.fr`)"
      - "traefik.http.routers.personal-frontend.entrypoints=websecure"
      - "traefik.http.routers.personal-frontend.tls=true"
      - "traefik.http.routers.personal-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.personal-frontend.loadbalancer.server.port=8080"
    networks:
      - proxy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal_backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.personal-backend.rule=Host(`mathislambert.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.personal-backend.entrypoints=websecure"
      - "traefik.http.routers.personal-backend.tls=true"
      - "traefik.http.routers.personal-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.personal-backend.loadbalancer.server.port=8081"
    networks:
      - proxy

networks:
  proxy:
    external: true
