export const LOGOS = {
  python: "/svgs/logos/python.svg",
  fastapi: "/svgs/logos/fastapi.svg",
  docker: "/svgs/logos/docker.svg",
  pycharm: "/svgs/logos/pycharm.svg",
  react: "/svgs/logos/react.svg",
  typescript: "/svgs/logos/typescript.svg",
  linux: "/svgs/logos/linux.svg",
  bashLight: "/svgs/logos/bash-light.svg",
  bashDark: "/svgs/logos/bash-dark.svg",
  tailwind: "/svgs/logos/tailwindcss.svg",
  githubLight: "/svgs/logos/github-light.svg",
  githubDark: "/svgs/logos/github-dark.svg",
  gitlab: "/svgs/logos/gitlab.svg",
  figma: "/svgs/logos/figma.svg",
  vite: "/svgs/logos/vite.svg",
  arc: "/svgs/logos/arc.svg",
  shadcnLight: "/svgs/logos/shadcn-light.svg",
  shadcnDark: "/svgs/logos/shadcn-dark.svg",
  mistralLight: "/svgs/logos/mistral_orange.svg",
  mistralDark: "/svgs/logos/mistral_alpha.svg",
  vllmColor: "/svgs/logos/vllm-color.svg",
  mongodb: "/svgs/logos/mongodb.svg",
  qdrant: "/svgs/logos/qdrant.svg",
  nvidia: "/svgs/logos/nvidia.svg",
  openaiLight: "/svgs/logos/openai-light.svg",
  openaiDark: "/svgs/logos/openai-dark.svg",
  huggingface: "/svgs/logos/huggingface.svg",
} as const;

export type LogoKey = keyof typeof LOGOS;
